#!/bin/bash -eu


# convert README.md to readme.rst
pandoc --column 500 -f markdown -t rst -o docs/readme.rst README.md


# auto-generate package guide
sphinx-apidoc -efT -o docs/_apidoc demonstration


# build website
sphinx-build -a docs docs/_build
